eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1010/eureka/
  instance:
    prefer-ip-address: true #使用ip进行注册
    instance-id: systemmanage-server
server:
  port: 2010
spring:
  application:
    name: systemmanage-server
